### ISSUE TITLE
pandas : ep_2, рефакторинг

### ISSUE THREAD

**Issue by avasyukov** [oitsumerarete/Python_labs#1]
1. (Важное) Вот это формально верно, но ручные циклы с ручной сборкой ответа сильно противоречат идеологии pandas-ов:
https://github.com/oitsumerarete/Python_labs/blob/a8e02a4cec492d887b9d86463bece144f40d8c46/lab_2/ep_2/cargo.py#L8-L16
Здесь очень нужен `groupby` и обработка его итогов.

2. (Минорное) Рисовать вот так вполне можно:
https://github.com/oitsumerarete/Python_labs/blob/a8e02a4cec492d887b9d86463bece144f40d8c46/lab_2/ep_2/cargo.py#L18-L31
Но после идейно верной сборки ответа сильно удобнее станет рисовать средствами pandas-ов. Примерно вот так: `(pandas-овый объект).plot(kind='bar', ax=ax[0], title="Number of flights")`.

**Comment by oitsumerarete** [comment]
Исправила
