### ISSUE TITLE
pandas : ep_3, лишние операции

### ISSUE THREAD

**Issue by avasyukov** [oitsumerarete/Python_labs#2]
Делать два раза один и тот же `groupby` ради извлечения один раз `index` и второй раз `values` точно не надо:
https://github.com/oitsumerarete/Python_labs/blob/a8e02a4cec492d887b9d86463bece144f40d8c46/lab_2/ep_3/contest.py#L11-L15

Это и про количество тяжёлых операций в коде, и про его общую читаемость.

**Comment by oitsumerarete** [comment]
Исправила
