### ISSUE TITLE
numpy : ep_1, скорость работы

### ISSUE THREAD

**Issue by avasyukov** [oitsumerarete/Python_labs#3]
Ручной обход матриц точно не нужен:
https://github.com/oitsumerarete/Python_labs/blob/a8e02a4cec492d887b9d86463bece144f40d8c46/lab_3/ep_1/moon.py#L16-L18

Это (а) максимально не фэн-шуйно в NumPy-ном коде, (б) на пару порядков медленнее, чем могло бы быть.

Нужны NumPy-ные broadcast-ы.

**Comment by oitsumerarete** [comment]
Исправила
